### ISSUE TITLE
Symfony 5 Support

### ISSUE THREAD

**Issue by tacman** [odiseoteam/OdiseoBlogBundle#6]
What are the plans to upgrade the bundle for use with Symfony 5?

**Comment by bigboss86** [comment]
Hi @tacman. We plan to upgrade to symfony 5 in the near future. Feel free to do a PR if you want to contribute. Thanks!

**Comment by tacman** [comment]
Does a demo project exist for the this bundle?  If so, I'll try to bump the demo to Symfony 5 and submit a PR on what I had to change.

Are you thinking of a new version for the bundle that only supports 4.4 and 5?  I'm finding that supporting anything older than 4.4 is a lot of work.

**Comment by odiseoteam** [comment]
Hi @tacman. We don't have a demo project for this bundle. Do you want to create a repo for that?
About the version, i think we can deprecate older versions than 4.4. What do you think?

**Comment by tacman** [comment]
I gave it a shot, but am stuck on Sylius.  Are they absolutely needed for
this bundle?

It looks like they're used to define the model and provide CRUD.  Can they
be removed?

**Comment by bigboss86** [comment]
New version released!
